### ISSUE TITLE
Error in Parser.php

### ISSUE THREAD

**Issue by donnekgit** [mdsills/cccedict#8]
When I run `php -f index.php`, get:
```
Fatal error: Default value for parameters with a class type hint can only be NULL in /var/www/pinyinhua/cccedict/src/CcCedict/Parser.php on line 72
```
How to fix?

**Comment by mdsills** [comment]
Hi!

(I've not confirmed it by trying, but) I think you're seeing this error due to running PHP5. As it stands, this code requires PHP7 (which supports scalar type hints.)

If you're unable to run PHP7, removing the scalar type hints (e.g. the "int" in "public function setBlockSize(int $blockSize = 50)") should move you past this error, but there are likely other PHP7-only aspects of the code. So, I guess my recommendation is to upgrade to PHP7 :)

I realise this isn't a solution, but i hope it helps...
